version: "3"
services:
    mongodb:
        image: "mongo:4.2"
        container_name: mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    redis:
        image: "redis:5.0-alpine"
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - "${REDIS_DIR}:/data"
        environment:
            - REDIS_DIR=${REDIS_DIR}